// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNOReyftr_VV0IgkeScvPvVjmLXrmqi3g',
    appId: '1:960289563794:web:d435f90a6a747ffa1bb24b',
    messagingSenderId: '960289563794',
    projectId: 'to-do-app-0912',
    authDomain: 'to-do-app-0912.firebaseapp.com',
    storageBucket: 'to-do-app-0912.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAws3sxXQ7nYi9cbvnaEGgySV0xzJm3Ku0',
    appId: '1:960289563794:android:25430c0ee1f53cee1bb24b',
    messagingSenderId: '960289563794',
    projectId: 'to-do-app-0912',
    storageBucket: 'to-do-app-0912.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCH93jZj_OSCBkfWI9v2j28v2ZQjmw2DY',
    appId: '1:960289563794:ios:ceef55c52e0a1b841bb24b',
    messagingSenderId: '960289563794',
    projectId: 'to-do-app-0912',
    storageBucket: 'to-do-app-0912.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCH93jZj_OSCBkfWI9v2j28v2ZQjmw2DY',
    appId: '1:960289563794:ios:ceef55c52e0a1b841bb24b',
    messagingSenderId: '960289563794',
    projectId: 'to-do-app-0912',
    storageBucket: 'to-do-app-0912.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNOReyftr_VV0IgkeScvPvVjmLXrmqi3g',
    appId: '1:960289563794:web:13b957739ba1c32a1bb24b',
    messagingSenderId: '960289563794',
    projectId: 'to-do-app-0912',
    authDomain: 'to-do-app-0912.firebaseapp.com',
    storageBucket: 'to-do-app-0912.appspot.com',
  );

}